CREATE ROLE wms_admin;
GRANT wms_admin TO wms_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wms_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO wms_admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO wms_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO wms_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO wms_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO wms_admin;